#Buisness Configurations
leaderboardDepth: 10
symbols:
  bitcoin:
    name: Bitcoin
    id: bitcoin
    symbol: BTC
    imagePath: https://cdn.pratikd.in/symbols/btc.png
  ethereum:
    name: Ethereum
    id: ethereum
    symbol: ETH
    imagePath: https://cdn.pratikd.in/symbols/eth.png
  solana:
    name: Solana
    id: solana
    symbol: SOL
    imagePath: https://cdn.pratikd.in/symbols/solana.png
  usdc:
    name: USDC
    id: usdc
    symbol: USDC
    imagePath: https://cdn.pratikd.in/symbols/usdc.png
  arbitrum:
    name: Arbitrum
    id: arbitrum
    symbol: ARB
    imagePath: https://cdn.pratikd.in/symbols/artbitrum.png