version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    command: ["make", "run"]
    ports:
      - 8080:8080
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      REDIS_ADDRESS: redis:6379

  redis:
    image: redis:alpine
    healthcheck:
        test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        interval: 10s
        timeout: 5s
        retries: 6
