definitions:
  models.Symbol:
    properties:
      id:
        type: string
      imagePath:
        type: string
      name:
        type: string
      symbol:
        type: string
    type: object
  models.UserTradeStat:
    properties:
      rank:
        type: integer
      totalVolume:
        type: number
      traderId:
        type: string
    type: object
info:
  contact: {}
paths:
  /leaderboard/{symbol}:
    get:
      consumes:
      - application/json
      description: Get the leaderboard for a given symbol.
      parameters:
      - description: Symbol
        in: path
        name: symbol
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.UserTradeStat'
            type: array
      summary: Get the leaderboard for a given symbol.
  /symbols:
    get:
      consumes:
      - application/json
      description: Get the list of symbols.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/models.Symbol'
            type: object
      summary: Get the list of symbols.
  /version:
    get:
      consumes:
      - application/json
      description: Get Version
      produces:
      - application/json
      responses: {}
      summary: Get Version
swagger: "2.0"
